### ISSUE TITLE
修改：漏网之鱼

### ISSUE THREAD

**Issue by Skr-ZERO** [NightFurySL2001/WD-XL-font#1]
“茛蝕谡亂覜”
简单改了一下，如果改的不好还请帮忙优化一下。
[滑油字.zip](https://github.com/NightFurySL2001/WD-XL-font/files/6564483/default.zip)

**Comment by NightFurySL2001** [comment]
已收到，谢谢你！

其中“茛谡”二字内部文件在发布当天后已经修改（还有其他类似反白字如`鋱谥踝`），“蝕”字也在猫啃网看见问题后先行修改，三字未作替换。另外二字“亂覜”已经合并至内部文件，预计跟随下一版本一并更新。

![image](https://user-images.githubusercontent.com/33471049/120072794-18620000-c0c8-11eb-9647-54718ab56ab4.png)

P/S: 修改字体后的字体如果可以只需要提供修改的字符（删除其他未修改字符），可以大量压缩文件体积方便合并。请见Readme的“贡献”部分。

**Comment by Skr-ZERO** [comment]
修正：
1.“宽”：原版《黄油体》的字形才是正确的。

2.“宮”：未进行45°斜角的处理。

3.“舰舱”：其他“舟”字旁的字“舟”第三笔都有勾，就这俩字没有。


4.“孟勐艋猛蜢锰錳”：不知道这个勾是不是故意没去掉的，如果效果不好可以保持原样。


5.“舞”：改动下方的“舛”。

6.含“黽”部件的“黽澠黿繩蠅竈鼉鼈鼇”9个字中，“澠蠅竈”无45°斜角，其余6字有斜角，做统一处理，如果效果不好可以保持原样。


7.“澜”右侧的“柬”。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NightFurySL2001/WD-XL-font"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NightFurySL2001/WD-XL-font] 修改：漏网之鱼5个 (#1)





 
已收到，谢谢你！
 
其中“茛谡”二字内部文件在发布当天后已经修改（还有其他类似反白字如鋱谥踝），“蝕”字也在猫啃网看见问题后先行修改，未作替换。另外二字已经合并至内部文件，预计跟随下一版本一并更新。
 

 
P/S: 修改字体后的字体如果可以只需要提供修改的字符（删除其他未修改字符），可以大量压缩文件体积方便合并。请见Readme的“贡献”部分。

**Comment by NightFurySL2001** [comment]
已确认问题并修改上述所有提出的汉字（除了“孟”视为原字体设计不移除竖尾，但是统一斜角处理），并顺便转一圈“皿”系列（除了“皿”本字）修改成无转角（原字体繁体使用的字形）。
![image](https://user-images.githubusercontent.com/33471049/120099087-210c1200-c16c-11eb-900c-d68f1cd61564.png)
唠：原字体的品质偏差，这类出bug的字形太多了，只能抓一个打一个……

**Comment by Skr-ZERO** [comment]
1.偶然发现“梘”字与“梖”太相近，于是我彻查了一下含“貝”“見”的字，改动了“梘狽蜆襯”4字字形，新增“梖𤞭蛽”3字。
2.“撼洱”未加45°角。
3.“為爲”“偽僞”两对字形一样，我参考市面上的几款综艺体字改了“為偽”二字，略丑，见谅。
4.“贯惯掼貴軎實墅”6字字形错误（“軎實”二字的错字形已移到正确的码位）
5.“咻”轮廓有问题。
6.“唐”轮廓里多了一个特别小的块……已删。
[WD-XL_LUBRIFONT-SC.zip](https://github.com/NightFurySL2001/WD-XL-font/files/6638035/WD-XL_LUBRIFONT-SC.zip)

P.S.“货贷”二字字形太相近，但是还没解决方案。

**Comment by NightFurySL2001** [comment]
已合并`咻墅實洱狽蜆貴軎𡪲𰹲蛽𤞭梖梘撼`，修改`惯掼唐`。“襯”因为TC使用不同字形，因此未合并，仅修改见部件。
3 的 “為爲”“偽僞” 目前暂时未合并，还在考虑字形因素而不使用“為”。
“货贷”可以参考繁体的区分方式，只是不确定是否统一。可能需要放弃“代”部件的统一性。
![image](https://user-images.githubusercontent.com/33471049/121702730-b8764b00-cb04-11eb-98ca-f2612ff0586c.png)

日前接收到制作日文假名的贡献，但碍于品质问题，目前在请另一位朋友进行修缮，可能需要等待许久。目前也在安排进行日文常用汉字及台客粤语常用汉字的补字计划，预计新增400字，但是近期在赶着完善糖圆体计划，因此暂且搁置本计划。

**Comment by UltimateAmitieKaiNiC** [comment]
缺字：摀

**Comment by NightFurySL2001** [comment]
@UltimateAmitieKaiNiC “摀”不在目前补字计划所涵盖的范围，后续也不会完整覆盖 Big5。

**Comment by NightFurySL2001** [comment]
已补上“摀”及其他字符修复，见1.200版。
