### ISSUE TITLE
未來計劃

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [NightFurySL2001/WD-XL-font#3]
現在滑油字更新了，希望未來可以出韓文字庫。
別忘了KR噢！

**Comment by NightFurySL2001** [comment]
滑油字没有计划出韩文版本，因为韩文日常多用谚文少用汉字，且本人未学习阅读过韩文，因此恕不制作韩文版。

若有意愿，您可以制作更新后做 pull request 合并，或电邮联络制作。本字体的JP版是由 @Skr-ZERO 提供字形，本人仅提供技术支援合并进字体内。

**Comment by UltimateAmitieKaiNiC** [comment]
可以按照“BM Jua”。
