### ISSUE TITLE
「飠」部件

### ISSUE THREAD

**Issue by CraftingTable629** [NightFurySL2001/WD-XL-font#5]
![螢幕截圖 2024-04-16 下午8 47 07](https://github.com/NightFurySL2001/WD-XL-font/assets/38877481/29545b31-febe-49df-811c-92edab13841c)
從圖能看見，JP版本的「飯、餅」兩字「飠」不一樣。是因為「餅」字不在常用漢字表內嗎？
因為從TC版本，「飯、餅」兩字是一樣的。
![螢幕截圖 2024-04-16 下午8 49 09](https://github.com/NightFurySL2001/WD-XL-font/assets/38877481/19d5a0fd-b314-4be6-9f85-7894714e439d)
那這樣來說，「飠」是不是少了一點？因為當初我在想少一點是不是字體設計的風格，但我看到JP裡面「餅」字的「飠」有一點，那我覺得這可能是個漏洞

**Comment by NightFurySL2001** [comment]
JP N （約對應 Adobe-Japan1 StdN）的「餅」是依據 JIS X 0213:2004 的字形繪製。該形（亼有橫+下兩橫）雖然更貼合實際字形，但是對該區域的灰度觀感有明顯負面影響，因此選擇保留原字體（黃油體）的設計風格。

如果使用的是 JP S（約對應 Adobe-Japan1 Std），「餅」是會用和 TC 一樣的字形的。一些漢字如源規格分離的「飮」vs「飲」，和 JIS X 0208:1983 （OpenType `jp83` 功能）的「餃」也是會顯示（亼有橫+下兩橫）的形態。

**Comment by CraftingTable629** [comment]
明白。感謝大佬解答
